/**
 * Worker bindings.
 *
 * `Cloudflare.Env` holds everything declared in `wrangler.jsonc` (generated by
 * `wrangler types`); the secrets are not declared there, so they are added here.
 */
export interface Env extends Cloudflare.Env {
  SESSION_SECRET: string;
  COMPOSIO_API_KEY: string;
  OPENAI_API_KEY: string;
  DEEPSEEK_API_KEY: string;
  EXA_API_KEY: string;
}
