/**
 * Worker bindings.
 *
 * `Cloudflare.Env` holds everything declared in `wrangler.jsonc` (generated by
 * `wrangler types`); the secrets are not declared there, so they are added here.
 */
export interface Env extends Cloudflare.Env {
  SESSION_SECRET: string;
  COMPOSIO_API_KEY: string;
  OPENAI_API_KEY: string;
  DEEPSEEK_API_KEY: string;
  EXA_API_KEY: string;
  /**
   * The Telegram application the user session logs in as, from my.telegram.org.
   * Issued against a Telegram account, not generatable, and the app's identity
   * to Telegram — so it is a secret like any other.
   */
  TELEGRAM_API_ID: string;
  TELEGRAM_API_HASH: string;
  /** Places the calls that read out phone-link codes. */
  TELNYX_API_KEY: string;
  /** The `whsec_` signing secret of the OpenAI webhook that announces phone calls. */
  OPENAI_WEBHOOK_SECRET: string;
  /**
   * The app's own Plaid keys, from the Plaid Dashboard, for the environment
   * `PLAID_ENV` names. Until they are set the Plaid row says bank linking isn't
   * available rather than failing, which is why `plaidConfig` checks them.
   */
  PLAID_CLIENT_ID: string;
  PLAID_SECRET: string;
  /** 32 random bytes, base64: the key the stored Plaid access tokens are sealed under. */
  PLAID_TOKEN_KEY: string;
}
